package View;


import Controller.ItemController;
import Controller.TransactionController;
import Model.ModelCustomer;
import Model.ModelTransaksi;
import java.util.ArrayList;
import javax.swing.JOptionPane;


import Controller.CustomerController;
import Model.ModelItem;
public class TambahTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form TambahTransaksi
     */
    public TambahTransaksi() {
        initComponents();
        
        jComboBox1.removeAllItems();
        ArrayList<ModelCustomer> listCustomer;
        CustomerController customerController = new CustomerController();
        listCustomer = customerController.getCustomerData();
        ArrayList<ModelCustomer> listCustomerSesuaiAdmin;
        listCustomerSesuaiAdmin = customerController.getCustomerDataSesuaiAdmin(listCustomer, Login.adminId);
        for(ModelCustomer customer : listCustomerSesuaiAdmin){
            int idCustomer =  customer.getIdCustomer();
            String idCustomerStr = ""+idCustomer;
            jComboBox1.addItem(idCustomerStr);
        }
        
        jComboBox2.removeAllItems();
        ItemController itemController = new ItemController();
        ArrayList<ModelItem> listItems;
        listItems = itemController.getItemData();
        String items=""; 
        for(ModelItem item : listItems){
            items = item.getItem();
            jComboBox2.addItem(items);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupLayanan = new javax.swing.ButtonGroup();
        groupStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        LabelTambahDataTransaksi = new javax.swing.JLabel();
        LabelIDPelanggan1 = new javax.swing.JLabel();
        LabelJenisLayanan = new javax.swing.JLabel();
        LabelStatus = new javax.swing.JLabel();
        LabelTgl = new javax.swing.JLabel();
        LabelJenisLayanan2 = new javax.swing.JLabel();
        buttonSimpan2 = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();
        buttonSelesai = new javax.swing.JRadioButton();
        buttonBelumSelesai = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        TextFieldJenisLayanan = new javax.swing.JTextField();
        TextFieldTanggal = new javax.swing.JTextField();
        LabelJenisLayanan4 = new javax.swing.JLabel();
        LabelJenisLayanan5 = new javax.swing.JLabel();
        TextFieldBerat = new javax.swing.JTextField();
        LabelJenisLayanan6 = new javax.swing.JLabel();
        LabelTotalHarga = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        HargaPerKg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(23, 23, 23));

        LabelTambahDataTransaksi.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LabelTambahDataTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        LabelTambahDataTransaksi.setText("Tambah Data Transaksi");

        LabelIDPelanggan1.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelIDPelanggan1.setForeground(new java.awt.Color(255, 255, 255));
        LabelIDPelanggan1.setText("ID Pelanggan");

        LabelJenisLayanan.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelJenisLayanan.setForeground(new java.awt.Color(255, 255, 255));
        LabelJenisLayanan.setText("Jenis Layanan");

        LabelStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        LabelStatus.setText("Status Pencucian");

        LabelTgl.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelTgl.setForeground(new java.awt.Color(255, 255, 255));
        LabelTgl.setText("Tanggal");

        LabelJenisLayanan2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelJenisLayanan2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJenisLayanan2.setText("Item");

        buttonSimpan2.setBackground(new java.awt.Color(48, 48, 48));
        buttonSimpan2.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan2.setText("Simpan");
        buttonSimpan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonSimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpan2ActionPerformed(evt);
            }
        });

        buttonKembali.setBackground(new java.awt.Color(48, 48, 48));
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("Kembali");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        buttonSelesai.setBackground(new java.awt.Color(23, 23, 23));
        groupStatus.add(buttonSelesai);
        buttonSelesai.setForeground(new java.awt.Color(255, 255, 255));
        buttonSelesai.setText("Selesai");

        buttonBelumSelesai.setBackground(new java.awt.Color(23, 23, 23));
        groupStatus.add(buttonBelumSelesai);
        buttonBelumSelesai.setForeground(new java.awt.Color(255, 255, 255));
        buttonBelumSelesai.setText("Belum Selesai");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Format: YYYY-MM-DD");

        TextFieldJenisLayanan.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldJenisLayanan.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldJenisLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldJenisLayananActionPerformed(evt);
            }
        });

        TextFieldTanggal.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldTanggal.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTanggalActionPerformed(evt);
            }
        });

        LabelJenisLayanan4.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelJenisLayanan4.setForeground(new java.awt.Color(255, 255, 255));
        LabelJenisLayanan4.setText("Harga per Kg:");

        LabelJenisLayanan5.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelJenisLayanan5.setForeground(new java.awt.Color(255, 255, 255));
        LabelJenisLayanan5.setText("Berat (Kg)");

        TextFieldBerat.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldBerat.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBeratActionPerformed(evt);
            }
        });

        LabelJenisLayanan6.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelJenisLayanan6.setForeground(new java.awt.Color(255, 255, 255));
        LabelJenisLayanan6.setText("Total Harga:");

        LabelTotalHarga.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelTotalHarga.setForeground(new java.awt.Color(255, 255, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        HargaPerKg.setBackground(new java.awt.Color(255, 255, 255));
        HargaPerKg.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJenisLayanan6)
                            .addComponent(LabelJenisLayanan5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTotalHarga)))
                    .addComponent(LabelTambahDataTransaksi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelStatus)
                            .addComponent(LabelTgl))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(buttonSelesai)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBelumSelesai))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(buttonSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJenisLayanan)
                            .addComponent(LabelIDPelanggan1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldJenisLayanan, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(LabelJenisLayanan4)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(LabelJenisLayanan2)
                                .addGap(77, 77, 77)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaPerKg))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTambahDataTransaksi)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDPelanggan1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJenisLayanan)
                    .addComponent(TextFieldJenisLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSelesai)
                        .addComponent(buttonBelumSelesai))
                    .addComponent(LabelStatus))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LabelTgl))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJenisLayanan2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJenisLayanan4)
                    .addComponent(HargaPerKg))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJenisLayanan5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJenisLayanan6)
                    .addComponent(LabelTotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        Home H = new Home();
        setVisible(false);
        H.setVisible(true);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonSimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpan2ActionPerformed
        // TODO add your handling code here:
        Object selectedValueCustomerId = jComboBox1.getSelectedItem();
        String TFidPelanggan = selectedValueCustomerId.toString();
        int idPelanggan = Integer.parseInt(TFidPelanggan);
        String jenisLayanan = TextFieldJenisLayanan.getText();
        String statusPencucian = "";
        try {
            if (groupStatus.getSelection().equals(buttonSelesai.getModel())) {
                statusPencucian = "Selesai";
            } else if (groupStatus.getSelection().equals(buttonBelumSelesai.getModel())) {
                statusPencucian = "Belum Selesai";
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }

        String tgl = TextFieldTanggal.getText();
        
        
        String TFHargaPerKg = HargaPerKg.getText();
        int HargaPerKg = Integer.parseInt(TFHargaPerKg);
        
        
        String TFBerat = TextFieldBerat.getText();
        float berat = Float.parseFloat(TFBerat);
        ModelTransaksi modelTransaksi = new ModelTransaksi();
        float totalF = modelTransaksi.HitungHarga(HargaPerKg, berat);
        String total = Float.toString(totalF);
        LabelTotalHarga.setText(total);
        
        
        ItemController itemController = new ItemController();
        Object SelectedValueItem = jComboBox2.getSelectedItem();
        String itemName = SelectedValueItem.toString();
        
        int idItem = itemController.getIdItem(itemName);
        
        TransactionController transactionController = new TransactionController();
        int idTransaksi = transactionController.getNextIdTransaksi();
        String noTransaksi = "T"+idTransaksi;
        
        String beratString = berat+" Kg";
        
        transactionController.insertTransaksi(idTransaksi, noTransaksi, jenisLayanan, statusPencucian, totalF, idPelanggan, idItem,Login.adminId, beratString, tgl);
        if(transactionController.adaTransaksi(idTransaksi)){
            JOptionPane.showMessageDialog(null, "Berhasil Menambah Transaksi");
        }else{
            JOptionPane.showMessageDialog(null, "Gagal Menambah Transaksi");
        }
    }//GEN-LAST:event_buttonSimpan2ActionPerformed

    private void TextFieldJenisLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldJenisLayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldJenisLayananActionPerformed

    private void TextFieldTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTanggalActionPerformed

    private void TextFieldBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBeratActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2 != null && jComboBox2.getSelectedItem() != null) {
            Object selectedItem = jComboBox2.getSelectedItem();
            String item = selectedItem.toString();
            ItemController itemController = new ItemController();
            int hargaPerKgInt = itemController.getHargaPerKg(item);
            String hargaPerKgStr = ""+hargaPerKgInt;
            HargaPerKg.setText(hargaPerKgStr);
        }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HargaPerKg;
    private javax.swing.JLabel LabelIDPelanggan1;
    private javax.swing.JLabel LabelJenisLayanan;
    private javax.swing.JLabel LabelJenisLayanan2;
    private javax.swing.JLabel LabelJenisLayanan4;
    private javax.swing.JLabel LabelJenisLayanan5;
    private javax.swing.JLabel LabelJenisLayanan6;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelTambahDataTransaksi;
    private javax.swing.JLabel LabelTgl;
    private javax.swing.JLabel LabelTotalHarga;
    private javax.swing.JTextField TextFieldBerat;
    private javax.swing.JTextField TextFieldJenisLayanan;
    private javax.swing.JTextField TextFieldTanggal;
    private javax.swing.JRadioButton buttonBelumSelesai;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JRadioButton buttonSelesai;
    private javax.swing.JButton buttonSimpan2;
    private javax.swing.ButtonGroup groupLayanan;
    private javax.swing.ButtonGroup groupStatus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
